# Generated by Django 5.0 on 2023-12-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='turf',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
