# Generated by Django 4.2.1 on 2023-12-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_booking_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='day',
        ),
    ]
