# Generated by Django 5.0 on 2023-12-21 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_booking_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(default='91', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.CharField(default='user', max_length=200),
        ),
    ]
