# Generated by Django 5.0 on 2023-12-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking_email_booking_phonenumber_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
